### ISSUE TITLE
'classes must be the same'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bmor1/bimserver#103]
```
the case:
- one project (no subprojects)
- one IFC upload
- export to KMZ
- intelligent merging is 'on'

getting the error below....
Important issue: with intelligent merging OFF, there are NO errors.




HTTP ERROR 500

Problem accessing /download. Reason:

    Classes must be the same
Caused by:

java.lang.RuntimeException: Classes must be the same
    at org.bimserver.database.actions.BimDatabaseAction.removeReplaceLinks(BimDatabaseAction.java:215)
    at org.bimserver.database.actions.BimDatabaseAction.cleanGuidMap(BimDatabaseAction.java:184)
    at org.bimserver.database.actions.BimDatabaseAction.mergeType(BimDatabaseAction.java:174)
    at org.bimserver.database.actions.BimDatabaseAction.merge(BimDatabaseAction.java:150)
    at org.bimserver.database.actions.DownloadDatabaseAction.execute(DownloadDatabaseAction.java:42)
    at org.bimserver.database.actions.DownloadDatabaseAction.execute(DownloadDatabaseAction.java:1)
    at org.bimserver.database.DatabaseSession.executeAction(DatabaseSession.java:132)
    at org.bimserver.Service.download(Service.java:633)
    at org.bimserver.shared.AuthenticatedServiceWrapper.download(AuthenticatedServiceWrapper.java:98)
    at org.bimserver.servlets.DownloadServlet.service(DownloadServlet.java:123)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:527)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:423)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:493)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:930)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:358)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:866)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:113)
    at org.eclipse.jetty.server.Server.handle(Server.java:351)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:594)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1059)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:764)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:217)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:424)
    at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:241)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:436)
    at java.lang.Thread.run(Thread.java:619)
Powered by Jetty://


















```

Original issue reported on code.google.com by `berlo...@gmail.com` on 23 Sep 2010 at 7:20

**Comment by GoogleCodeExporter** [comment]
```
This bug should have been fixed, but I cannot test it because this is a file 
specific issue (same GUID for different types of objects), Leon, which file was 
causing this?
```

Original comment by `rdlsoftware@gmail.com` on 23 Sep 2010 at 10:18

**Comment by GoogleCodeExporter** [comment]
```
Merging is now being skipped when there is only 1 model, bug does not occur 
anymore.
```

Original comment by `rdlsoftware@gmail.com` on 23 Sep 2010 at 10:57

**Comment by GoogleCodeExporter** [comment]
Original comment by `rdlsoftware@gmail.com` on 23 Sep 2010 at 10:59
- Changed state: **Fixed**
