### ISSUE TITLE
Collada export fails on ubuntu linux (10.4) 32 bit.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bmor1/bimserver#123]
```
What steps will reproduce the problem?
1. Download bimserver trunk as of Nov 11 2010
2. Create a new project with a subproject. Upload the 
"AC11-Institute-Var-2-IFC.ifc" from testdata\data
3. Try to download a collada .dae or .kmz file, or try to open the webGL 
version in bimserver.
4. Look at the file and the log from the bimserver. 

Please have a look at the .coe and .kmz files attached.

What is the expected output? What do you see instead?
The collada file seems to be nearly empty. GoogleEarth complains ""Error: could 
not understand file" on ".../files/collada.dae"
Nothing shows up in the webgl browser version. (using chrome 7 with 
--enable-webgl)


What version of the product are you using? On what operating system?
-bimserver trunk as of nov 11 2010
-Ubuntu 10.4 32 bit

Please provide any additional information below.
Log from bimserver:

2010-11-11 13:38:29,799 INFO  
org.bimserver.database.berkeley.BerkeleyColumnDatabase - reads: 300000
2010-11-11 13:39:16,637 INFO  org.bimserver.ifcengine.IfcEngineProcess - java 
-Djna.library.path=lib/32 
-Djava.io.tmpdir=/home/user/eclipse-helios/BimServer/build/builds/bimserver-1.0R
C3/tmp -classpath 
/home/user/eclipse-helios/BimServer/build/builds/bimserver-1.0RC3/lib/slf4j-log4
j12-1.6.0.jar:/home/user/eclipse-helios/BimServer/build/builds/bimserver-1.0RC3/
lib/slf4j-api-1.6.0.jar:/home/user/eclipse-helios/BimServer/build/builds/bimserv
er-1.0RC3/lib/log4j-1.2.16.jar:/home/user/eclipse-helios/BimServer/build/builds/
bimserver-1.0RC3/lib/bimserver.jar:/home/user/eclipse-helios/BimServer/build/bui
lds/bimserver-1.0RC3/lib/jna.jar:/home/user/eclipse-helios/BimServer/build/build
s/bimserver-1.0RC3/lib/org.eclipse.emf_2.5.0.v200906151043.jar:/home/user/eclips
e-helios/BimServer/build/builds/bimserver-1.0RC3/lib/org.eclipse.emf.common_2.5.
0.v200906151043.jar:/home/user/eclipse-helios/BimServer/build/builds/bimserver-1
.0RC3/lib/org.eclipse.emf.ecore_2.5.0.v200906151043.jar:/home/user/eclipse-helio
s/BimServer/build/builds/bimserver-1.0RC3/lib/org.eclipse.emf.ecore.xmi_2.5.0.v2
00906151043.jar: -Xmx512m org.bimserver.ifcengine.IfcEngineServer 
/home/user/eclipse-helios/BimServer/build/builds/bimserver-1.0RC3/config/IFC2X3_
FINAL.exp
2010-11-11 13:39:17,526 ERROR org.bimserver.collada.ColladaSerializer - 
org.bimserver.ifcengine.IfcEngineException: Unknown IFC Engine error
    at org.bimserver.ifcengine.FailSafeIfcEngine.flush(FailSafeIfcEngine.java:72)
    at org.bimserver.ifcengine.IfcEngineModel.close(IfcEngineModel.java:86)
    at org.bimserver.collada.ColladaSerializer.setGeometry(ColladaSerializer.java:305)
    at org.bimserver.collada.ColladaSerializer.writeGeometries(ColladaSerializer.java:166)
    at org.bimserver.collada.ColladaSerializer.write(ColladaSerializer.java:96)
    at org.bimserver.ifc.EmfSerializer.writeToOutputStream(EmfSerializer.java:133)
    at org.bimserver.servlets.DownloadServlet.service(DownloadServlet.java:148)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:527)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:423)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:493)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:930)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:358)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:866)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:113)
    at org.eclipse.jetty.server.Server.handle(Server.java:351)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:594)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1059)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:764)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:217)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:424)
    at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:241)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:436)
    at java.lang.Thread.run(Thread.java:662)
2010-11-11 13:39:17,527 ERROR org.bimserver.ifcengine.FailSafeIfcEngine - 
org.bimserver.ifcengine.IfcEngineException: Unknown IFC Engine error
    at org.bimserver.ifcengine.FailSafeIfcEngine.flush(FailSafeIfcEngine.java:72)
    at org.bimserver.ifcengine.FailSafeIfcEngine.close(FailSafeIfcEngine.java:96)
    at org.bimserver.collada.ColladaSerializer.write(ColladaSerializer.java:107)
    at org.bimserver.ifc.EmfSerializer.writeToOutputStream(EmfSerializer.java:133)
    at org.bimserver.servlets.DownloadServlet.service(DownloadServlet.java:148)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:527)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:423)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:493)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:930)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:358)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:866)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:113)
    at org.eclipse.jetty.server.Server.handle(Server.java:351)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:594)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1059)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:764)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:217)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:424)
    at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:241)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:436)
    at java.lang.Thread.run(Thread.java:662)

```

Original issue reported on code.google.com by `Lars.Bjo...@gmail.com` on 11 Nov 2010 at 12:59

Attachments:
- [ARK2.1.dae](https://storage.googleapis.com/google-code-attachments/bimserver/issue-123/comment-0/ARK2.1.dae)
- [ARK2.1.kmz](https://storage.googleapis.com/google-code-attachments/bimserver/issue-123/comment-0/ARK2.1.kmz)

**Comment by GoogleCodeExporter** [comment]
Original comment by `berlo...@gmail.com` on 12 Nov 2010 at 8:20
- Changed state: **Fixed**
