### ISSUE TITLE
revision does not exist

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bmor1/bimserver#173]
```
What steps will reproduce the problem?
1. upload IFC
2. during 'storing' click on 'projects' (or the logo)
3.

What is the expected output? What do you see instead?
expect to see projectslist with a revision.


instead: get an error (see screenshot)
after waiting a while (till the storing is done) everything works fine again.


log:
2010-12-14 11:33:15,573 INFO  org.bimserver.Server - Webserver successfully 
started
2010-12-14 11:33:15,573 INFO  org.bimserver.Server - Server started 
successfully, click on the "launch webbrowser" button, or go to: 
http://localhost:8082
2010-12-14 11:40:04,429 INFO  
org.bimserver.database.berkeley.BerkeleyColumnDatabase - writes: 100000
2010-12-14 11:40:07,232 ERROR 
org.bimserver.database.berkeley.BerkeleyColumnDatabase - 
com.sleepycat.je.LockTimeoutException: (JE 4.1.6) Lock expired. Locker 
966333165 -1_qtp163638423-11_ReadCommittedLocker: waited for lock on 
database=Revision LockAddr:1890165541 node=3489 type=READ grant=WAIT_NEW 
timeoutMillis=5000 startTime=1292323202230 endTime=1292323207230
Owners: [<LockInfo locker="584088179 1519_LongActionManager_Txn" type="WRITE"/>]
Waiters: []

    at com.sleepycat.je.txn.LockManager.newLockTimeoutException(LockManager.java:608)
    at com.sleepycat.je.txn.LockManager.makeTimeoutMsgInternal(LockManager.java:567)
    at com.sleepycat.je.txn.SyncedLockManager.makeTimeoutMsg(SyncedLockManager.java:75)
    at com.sleepycat.je.txn.LockManager.lockInternal(LockManager.java:385)
    at com.sleepycat.je.txn.LockManager.lock(LockManager.java:272)
    at com.sleepycat.je.txn.BasicLocker.lockInternal(BasicLocker.java:134)
    at com.sleepycat.je.txn.ReadCommittedLocker.lockInternal(ReadCommittedLocker.java:90)
    at com.sleepycat.je.txn.Locker.lock(Locker.java:453)
    at com.sleepycat.je.dbi.CursorImpl.lockLNDeletedAllowed(CursorImpl.java:2696)
    at com.sleepycat.je.dbi.CursorImpl.lockLN(CursorImpl.java:2615)
    at com.sleepycat.je.dbi.CursorImpl.searchAndPosition(CursorImpl.java:2267)
    at com.sleepycat.je.Cursor.searchInternal(Cursor.java:2097)
    at com.sleepycat.je.Cursor.searchAllowPhantoms(Cursor.java:2067)
    at com.sleepycat.je.Cursor.search(Cursor.java:1935)
    at com.sleepycat.je.Database.get(Database.java:905)
    at org.bimserver.database.berkeley.BerkeleyColumnDatabase.get(BerkeleyColumnDatabase.java:173)
    at org.bimserver.database.DatabaseSession.get(DatabaseSession.java:332)
    at org.bimserver.database.DatabaseSession.get(DatabaseSession.java:326)
    at org.bimserver.database.DatabaseSession.get(DatabaseSession.java:1127)
    at org.bimserver.database.DatabaseSession.getRevisionByRoid(DatabaseSession.java:1116)
    at org.bimserver.database.actions.GetRevisionDatabaseAction.execute(GetRevisionDatabaseAction.java:26)
    at org.bimserver.database.actions.GetRevisionDatabaseAction.execute(GetRevisionDatabaseAction.java:13)
    at org.bimserver.database.DatabaseSession.executeAction(DatabaseSession.java:137)
    at org.bimserver.webservices.Service.getRevision(Service.java:683)
    at org.bimserver.web.JspHelper.writeProjectTree(JspHelper.java:53)
    at org.bimserver.web.JspHelper.writeProjectTree(JspHelper.java:88)
    at org.apache.jsp.main_jsp._jspService(org.apache.jsp.main_jsp:244)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:109)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:389)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:486)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:380)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:527)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:423)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:493)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:930)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:358)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:866)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:113)
    at org.eclipse.jetty.server.Server.handle(Server.java:351)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:594)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1042)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:549)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:211)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:424)
    at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:241)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:436)
    at java.lang.Thread.run(Thread.java:680)
2010-12-14 11:40:07,242 WARN  org.eclipse.jetty.util.log - /main.jsp
org.bimserver.shared.UserException: Revision does not exist
    at org.bimserver.database.actions.GetRevisionDatabaseAction.execute(GetRevisionDatabaseAction.java:28)
    at org.bimserver.database.actions.GetRevisionDatabaseAction.execute(GetRevisionDatabaseAction.java:13)
    at org.bimserver.database.DatabaseSession.executeAction(DatabaseSession.java:137)
    at org.bimserver.webservices.Service.getRevision(Service.java:683)
    at org.bimserver.web.JspHelper.writeProjectTree(JspHelper.java:53)
    at org.bimserver.web.JspHelper.writeProjectTree(JspHelper.java:88)
    at org.apache.jsp.main_jsp._jspService(org.apache.jsp.main_jsp:244)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:109)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:389)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:486)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:380)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:527)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:423)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:493)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:930)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:358)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:866)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:113)
    at org.eclipse.jetty.server.Server.handle(Server.java:351)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:594)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1042)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:549)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:211)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:424)
    at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:241)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:436)
    at java.lang.Thread.run(Thread.java:680)
2010-12-14 11:40:13,050 INFO  
org.bimserver.database.berkeley.BerkeleyColumnDatabase - writes: 200000
2010-12-14 11:40:16,496 ERROR 
org.bimserver.database.berkeley.BerkeleyColumnDatabase - 
com.sleepycat.je.LockTimeoutException: (JE 4.1.6) Lock expired. Locker 
1316095982 -1_qtp163638423-11_ReadCommittedLocker: waited for lock on 
database=Revision LockAddr:1890165541 node=3489 type=READ grant=WAIT_NEW 
timeoutMillis=5000 startTime=1292323211496 endTime=1292323216496
Owners: [<LockInfo locker="584088179 1519_LongActionManager_Txn" type="WRITE"/>]
Waiters: [<LockInfo locker="543605374 -1_qtp163638423-16_ReadCommittedLocker" 
type="READ"/>]

    at com.sleepycat.je.txn.LockManager.newLockTimeoutException(LockManager.java:608)
    at com.sleepycat.je.txn.LockManager.makeTimeoutMsgInternal(LockManager.java:567)
    at com.sleepycat.je.txn.SyncedLockManager.makeTimeoutMsg(SyncedLockManager.java:75)
    at com.sleepycat.je.txn.LockManager.lockInternal(LockManager.java:385)
    at com.sleepycat.je.txn.LockManager.lock(LockManager.java:272)
    at com.sleepycat.je.txn.BasicLocker.lockInternal(BasicLocker.java:134)
    at com.sleepycat.je.txn.ReadCommittedLocker.lockInternal(ReadCommittedLocker.java:90)
    at com.sleepycat.je.txn.Locker.lock(Locker.java:453)
    at com.sleepycat.je.dbi.CursorImpl.lockLNDeletedAllowed(CursorImpl.java:2696)
    at com.sleepycat.je.dbi.CursorImpl.lockLN(CursorImpl.java:2615)
    at com.sleepycat.je.dbi.CursorImpl.searchAndPosition(CursorImpl.java:2267)
    at com.sleepycat.je.Cursor.searchInternal(Cursor.java:2097)
    at com.sleepycat.je.Cursor.searchAllowPhantoms(Cursor.java:2067)
    at com.sleepycat.je.Cursor.search(Cursor.java:1935)
    at com.sleepycat.je.Database.get(Database.java:905)
    at org.bimserver.database.berkeley.BerkeleyColumnDatabase.get(BerkeleyColumnDatabase.java:173)
    at org.bimserver.database.DatabaseSession.get(DatabaseSession.java:332)
    at org.bimserver.database.DatabaseSession.get(DatabaseSession.java:326)
    at org.bimserver.database.DatabaseSession.get(DatabaseSession.java:1127)
    at org.bimserver.database.DatabaseSession.getRevisionByRoid(DatabaseSession.java:1116)
    at org.bimserver.database.actions.GetRevisionDatabaseAction.execute(GetRevisionDatabaseAction.java:26)
    at org.bimserver.database.actions.GetRevisionDatabaseAction.execute(GetRevisionDatabaseAction.java:13)
    at org.bimserver.database.DatabaseSession.executeAction(DatabaseSession.java:137)
    at org.bimserver.webservices.Service.getRevision(Service.java:683)
    at org.bimserver.servlets.ProgressServlet.service(ProgressServlet.java:35)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:527)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:423)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:493)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:930)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:358)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:866)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:113)
    at org.eclipse.jetty.server.Server.handle(Server.java:351)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:594)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1042)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:549)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:211)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:424)
    at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:241)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:436)
    at java.lang.Thread.run(Thread.java:680)
2010-12-14 11:40:16,525 ERROR org.bimserver.servlets.ProgressServlet - 
org.bimserver.shared.UserException: Revision does not exist
    at org.bimserver.database.actions.GetRevisionDatabaseAction.execute(GetRevisionDatabaseAction.java:28)
    at org.bimserver.database.actions.GetRevisionDatabaseAction.execute(GetRevisionDatabaseAction.java:13)
    at org.bimserver.database.DatabaseSession.executeAction(DatabaseSession.java:137)
    at org.bimserver.webservices.Service.getRevision(Service.java:683)
    at org.bimserver.servlets.ProgressServlet.service(ProgressServlet.java:35)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:527)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:423)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:493)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:930)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:358)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:866)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:113)
    at org.eclipse.jetty.server.Server.handle(Server.java:351)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:594)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1042)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:549)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:211)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:424)
    at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:241)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:436)
    at java.lang.Thread.run(Thread.java:680)
```

Original issue reported on code.google.com by `berlo...@gmail.com` on 14 Dec 2010 at 10:45

Attachments:
- [Screen shot 2010-12-14 at 11.44.04 AM.png](https://storage.googleapis.com/google-code-attachments/bimserver/issue-173/comment-0/Screen shot 2010-12-14 at 11.44.04 AM.png)

**Comment by GoogleCodeExporter** [comment]
```
I also get the 'revision doesnt exist'  error in the console during normal use 
(not clicking something else during storing)

```

Original comment by `berlo...@gmail.com` on 14 Dec 2010 at 10:54

**Comment by GoogleCodeExporter** [comment]
Original comment by `ru...@logic-labs.nl` on 15 Dec 2010 at 11:59
- Changed state: **Fixed**
