### ISSUE TITLE
KMZ export on apple

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bmor1/bimserver#201]
```
Halfway the model export the console returns the error:

2011-01-20 14:26:00,802 ERROR org.bimserver.collada.KmzSerializer - 
org.eclipse.jetty.io.EofException
    at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:142)
    at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:86)
    at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:161)
    at java.util.zip.ZipOutputStream.closeEntry(ZipOutputStream.java:196)
    at org.bimserver.collada.KmzSerializer.write(KmzSerializer.java:50)
    at org.bimserver.ifc.EmfSerializer.writeToOutputStream(EmfSerializer.java:137)
    at org.bimserver.servlets.DownloadServlet.service(DownloadServlet.java:175)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:527)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:423)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:493)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:930)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:358)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:866)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:113)
    at org.eclipse.jetty.server.Server.handle(Server.java:351)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:594)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1042)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:549)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:211)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:424)
    at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:241)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:436)
    at java.lang.Thread.run(Thread.java:680)
```

Original issue reported on code.google.com by `berlo...@gmail.com` on 20 Jan 2011 at 1:28

**Comment by GoogleCodeExporter** [comment]
Original comment by `berlo...@gmail.com` on 27 Jan 2011 at 2:24
- Changed state: **Invalid**
