### ISSUE TITLE
Collada export fails on ubuntu linux (10.10) 64 bit.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bmor1/bimserver#253]
```
NOTE: This is most likely the same bug as this: 
http://code.google.com/p/bimserver/issues/detail?id=123 Only this time it's 64 
bit system and Ubuntu 10.10.

What steps will reproduce the problem?
1. Download bimserver trunk as of Nov 11 2010
2. Create a new project with a subproject. Upload the 
"AC11-Institute-Var-2-IFC.ifc" from testdata\data
3. Try to download a collada .dae file.
4. Look at the file and the log from the bimserver.  

What is the expected output? What do you see instead?
The collada file seems to be nearly empty. It ends with:
    </library_effects>
    <library_geometries> 
The whole geometry is missing.

What version of the product are you using? On what operating system?
- Branch 1.0 of bimserver updated monday 2011.03.27
- Ubuntu 10.10 64 bit

Please provide any additional information below.
Output from bimserver:
2011-03-30 22:13:46,597 INFO  
org.bimserver.database.berkeley.BerkeleyColumnDatabase - reads: 100000
2011-03-30 22:13:47,108 INFO  org.bimserver.ifcengine.FailSafeIfcEngine - java 
-Djna.library.path=/home/lbj/Utvikling/helios-catenda-bimserver/BimServer/build/
builds/bimserver-1.0RC3/lib/64 
-Djava.io.tmpdir=/home/lbj/Utvikling/helios-catenda-bimserver/BimServer/build/bu
ilds/bimserver-1.0RC3/tmp -classpath 
"lib:lib/jaxb-xjc-2.2.1.1.jar:lib/xalan-2.7.1.jar:lib/spring-tx-3.0.5.RELEASE.ja
r:lib/activation.jar:lib/aopalliance-1.0.jar:lib/slf4j-log4j12-1.6.0.jar:lib/saa
j-api-1.3.jar:lib/commons-fileupload-1.2.1.jar:lib/geronimo-ws-metadata_2.0_spec
-1.1.3.jar:lib/json.jar:lib/commons-logging-1.1.1.jar:lib/log4j-1.2.16.jar:lib/j
etty-websocket-7.1.6.v20100715.jar:lib/org.apache.taglibs.standard.glassfish_1.2
.0.v201004190952.jar:lib/jetty-policy-7.1.6.v20100715.jar:lib/jaxb-api-2.2.1.jar
:lib/jetty-annotations-7.1.6.v20100715.jar:lib/spring-core-3.0.5.RELEASE.jar:lib
/org.apache.jasper.glassfish_2.1.0.v201007080150.jar:lib/antlr-3.1.1-runtime.jar
:lib/cxf-2.3.2.jar:lib/saaj-impl-1.3.2.jar:lib/rome-1.0.jar:lib/commons-pool-1.5
.5.jar:lib/geronimo-annotation_1.0_spec-1.1.1.jar:lib/jetty-servlets-7.1.6.v2010
0715.jar:lib/jetty-jndi-7.1.6.v20100715.jar:lib/jsr173_1.0_api.jar:lib/StPL96.ja
r:lib/bcprov-jdk15-1.45.jar:lib/cxf-manifest.jar:lib/commons-pool-1.5.2.jar:lib/
joda-time-1.6.jar:lib/org.eclipse.emf.common_2.5.0.v200906151043.jar:lib/xbean.j
ar:lib/XmlSchema-1.4.7.jar:lib/jetty-io-7.1.6.v20100715.jar:lib/tar.jar:lib/seri
alizer-2.7.1.jar:lib/spring-beans-3.0.5.RELEASE.jar:lib/jetty-util-7.1.6.v201007
15.jar:lib/jetty-rewrite-7.1.6.v20100715.jar:lib/spring-web-3.0.5.RELEASE.jar:li
b/quartz-1.8.3.jar:lib/jna.jar:lib/antlr-2.7.7.jar:lib/commons-io-1.4.jar:lib/lo
g4j.xml:lib/je-4.1.6.jar:lib/wsdl4j-1.6.2.jar:lib/commons-lang-2.4.jar:lib/jetty
-webapp-7.1.6.v20100715.jar:lib/org.eclipse.emf_2.5.0.v200906151043.jar:lib/antl
r-3.2.jar:lib/jaxb-impl-2.2.1.1.jar:lib/jra-1.0-alpha-4.jar:lib/org.eclipse.emf.
ecore_2.5.0.v200906151043.jar:lib/jaxb1-impl.jar:lib/spring-expression-3.0.5.REL
EASE.jar:lib/xmlbeans-2.4.0.jar:lib/jsr311-api-1.1.1.jar:lib/jaxb-api.jar:lib/jd
om-1.0.jar:lib/java-getopt-1.0.13.jar:lib/jetty-jsp-2.1-7.1.6.v20100715.jar:lib/
xmlsec-1.4.4.jar:lib/cxf-xjc-ts-2.3.2.jar:lib/cxf-xjc-boolean-2.3.2.jar:lib/jett
y-plus-7.1.6.v20100715.jar:lib/jetty-xml-7.1.6.v20100715.jar:lib/antlr-runtime-3
.2.jar:lib/asm-3.3.jar:lib/jetty-jmx-7.1.6.v20100715.jar:lib/woodstox-core-asl-4
.0.8.jar:lib/spring-jms-3.0.5.RELEASE.jar:lib/js-1.7R2.jar:lib/geoapi-pending-2.
3-M1.jar:lib/neethi-2.0.4.jar:lib/jaxb-xjc.jar:lib/jetty-http-7.1.6.v20100715.ja
r:lib/ifcNamespaces.jar:lib/javax.servlet.jsp_2.1.0.v201004190952.jar:lib/ecj-3.
6.jar:lib/jetty-deploy-7.1.6.v20100715.jar:lib/jetty-server-7.1.6.v20100715.jar:
lib/commons-collections-3.2.1.jar:lib/jettison-1.2.jar:lib/cxf-xjc-bug671-2.3.2.
jar:lib/mail.jar:lib/oro-2.0.8.jar:lib/jetty-servlet-7.1.6.v20100715.jar:lib/slf
4j-api-1.6.0.jar:lib/velocity-1.6.4.jar:lib/bimserver.jar:lib/jetty-security-7.1
.6.v20100715.jar:lib/servlet-api-2.5.jar:lib/cxf-xjc-dv-2.3.2.jar:lib/geronimo-s
tax-api_1.0_spec-1.0.1.jar:lib/stringtemplate-3.2.jar:lib/javax.servlet.jsp.jstl
_1.2.0.v201004190952.jar:lib/spring-aop-3.0.5.RELEASE.jar:lib/citygml4j-0.2.1.ja
r:lib/spring-context-3.0.5.RELEASE.jar:lib/jaxb-impl.jar:lib/jetty-continuation-
7.1.6.v20100715.jar:lib/geronimo-jaxws_2.2_spec-1.0.jar:lib/geoapi-2.3-M1.jar:li
b/commons-lang-2.5.jar:lib/xmlbeans-qname.jar:lib/xbean_xpath.jar:lib/jettison-1
.0.1.jar:lib/geronimo-javamail_1.4_spec-1.7.1.jar:lib/resolver.jar:lib/jetty-ajp
-7.1.6.v20100715.jar:lib/com.sun.el_1.0.0.v201004190952.jar:lib/spring-asm-3.0.5
.RELEASE.jar:lib/geronimo-activation_1.1_spec-1.1.jar:lib/FastInfoset-1.2.8.jar:
lib/commons-codec-1.3.jar:lib/geronimo-servlet_3.0_spec-1.0.jar:lib/geronimo-jms
_1.1_spec-1.1.1.jar:lib/jetty-client-7.1.6.v20100715.jar:lib/stax2-api-3.0.2.jar
:lib/org.eclipse.emf.ecore.xmi_2.5.0.v200906151043.jar:lib/antlr-3.1.1.jar:lib/x
mlpublic.jar:lib/javax.el_2.1.0.v201004190952.jar:lib/guava-r07.jar:lib/xml-reso
lver-1.2.jar:lib/wss4j-1.5.11.jar:" -Xmx512m 
org.bimserver.ifcengine.jvm.IfcEngineServer 
/home/lbj/Utvikling/helios-catenda-bimserver/BimServer/build/builds/bimserver-1.
0RC3/config/IFC2X3_FINAL.exp
2011-03-30 22:13:47,460 ERROR org.bimserver.ifcengine.FailSafeIfcEngine - 
Exception in thread "main" 
2011-03-30 22:13:47,460 ERROR org.bimserver.ifcengine.FailSafeIfcEngine - 
java.lang.UnsatisfiedLinkError: Unable to load library 'IFCEngine': 
libIFCEngine.so: cannot open shared object file: No such file or directory
2011-03-30 22:13:47,460 ERROR org.bimserver.ifcengine.FailSafeIfcEngine - 

2011-03-30 22:13:47,460 ERROR org.bimserver.ifcengine.FailSafeIfcEngine -   at 
com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:164)
2011-03-30 22:13:47,460 ERROR org.bimserver.ifcengine.FailSafeIfcEngine - 

2011-03-30 22:13:47,460 ERROR org.bimserver.ifcengine.FailSafeIfcEngine -   at 
com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:237)
2011-03-30 22:13:47,461 ERROR org.bimserver.ifcengine.FailSafeIfcEngine - 

2011-03-30 22:13:47,461 ERROR org.bimserver.ifcengine.FailSafeIfcEngine -   at 
com.sun.jna.Library$Handler.<init>(Library.java:140)
2011-03-30 22:13:47,461 ERROR org.bimserver.ifcengine.FailSafeIfcEngine - 

2011-03-30 22:13:47,461 ERROR org.bimserver.ifcengine.FailSafeIfcEngine -   at 
com.sun.jna.Native.loadLibrary(Native.java:375)
2011-03-30 22:13:47,461 ERROR org.bimserver.ifcengine.FailSafeIfcEngine - 

2011-03-30 22:13:47,461 ERROR org.bimserver.ifcengine.FailSafeIfcEngine -   at 
com.sun.jna.Native.loadLibrary(Native.java:360)
2011-03-30 22:13:47,461 ERROR org.bimserver.ifcengine.FailSafeIfcEngine - 

2011-03-30 22:13:47,461 ERROR org.bimserver.ifcengine.FailSafeIfcEngine -   at 
org.bimserver.ifcengine.IfcEngineInterface.<clinit>(IfcEngineInterface.java:16)
2011-03-30 22:13:47,461 ERROR org.bimserver.ifcengine.FailSafeIfcEngine - 

2011-03-30 22:13:47,462 ERROR org.bimserver.ifcengine.FailSafeIfcEngine -   at 
org.bimserver.ifcengine.jvm.IfcEngine.<init>(IfcEngine.java:44)
2011-03-30 22:13:47,462 ERROR org.bimserver.ifcengine.FailSafeIfcEngine - 

2011-03-30 22:13:47,462 ERROR org.bimserver.ifcengine.FailSafeIfcEngine -   at 
org.bimserver.ifcengine.jvm.IfcEngineServer.<init>(IfcEngineServer.java:45)
2011-03-30 22:13:47,462 ERROR org.bimserver.ifcengine.FailSafeIfcEngine - 

2011-03-30 22:13:47,462 ERROR org.bimserver.ifcengine.FailSafeIfcEngine -   at 
org.bimserver.ifcengine.jvm.IfcEngineServer.main(IfcEngineServer.java:37)
2011-03-30 22:13:47,462 ERROR org.bimserver.ifcengine.FailSafeIfcEngine - 

2011-03-30 22:13:47,477 ERROR org.bimserver.collada.ColladaSerializer - 
org.bimserver.ifcengine.IfcEngineException: Unknown IFC Engine error
    at org.bimserver.ifcengine.FailSafeIfcEngine.readInt(FailSafeIfcEngine.java:155)
    at org.bimserver.ifcengine.FailSafeIfcEngine.openModel(FailSafeIfcEngine.java:147)
    at org.bimserver.ifcengine.FailSafeIfcEngine.openModel(FailSafeIfcEngine.java:244)
    at org.bimserver.collada.ColladaSerializer.setGeometry(ColladaSerializer.java:246)
    at org.bimserver.collada.ColladaSerializer.writeGeometries(ColladaSerializer.java:197)
    at org.bimserver.collada.ColladaSerializer.write(ColladaSerializer.java:96)
    at org.bimserver.ifc.EmfSerializer.writeToOutputStream(EmfSerializer.java:137)
    at org.bimserver.servlets.DownloadServlet.service(DownloadServlet.java:175)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:527)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:423)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:493)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:930)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:358)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:866)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:113)
    at org.eclipse.jetty.server.Server.handle(Server.java:351)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:594)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1042)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:549)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:211)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:424)
    at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:241)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:436)
    at java.lang.Thread.run(Thread.java:662)

```

Original issue reported on code.google.com by `lars.bjo...@catenda.no` on 30 Mar 2011 at 9:51

Attachments:
- [Test.1.dae](https://storage.googleapis.com/google-code-attachments/bimserver/issue-253/comment-0/Test.1.dae)

**Comment by GoogleCodeExporter** [comment]
```
Please ignore step 1. above. I simply copied the text from my last ticket and 
forgot to change that part. The error is still present on the current 1.0 
branch. (as of Monday 2011.03.27)
```

Original comment by `lars.bjo...@catenda.no` on 31 Mar 2011 at 8:53

**Comment by GoogleCodeExporter** [comment]
Original comment by `ru...@logic-labs.nl` on 31 Mar 2011 at 9:42
- Added labels: **Milestone-Release1.1**

**Comment by GoogleCodeExporter** [comment]
```
The bug was my own fault, due to missing .so files in the IfcEngine/lib/64 
folder. Thank you for pointing me to the problem Ruben!. You can close this bug 
report now.
```

Original comment by `lars.bjo...@catenda.no` on 31 Mar 2011 at 10:13

**Comment by GoogleCodeExporter** [comment]
Original comment by `ru...@logic-labs.nl` on 4 Apr 2011 at 8:44
- Changed state: **Close**
