### ISSUE TITLE
IFC Engine on OSX (64bit)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bmor1/bimserver#26]
```
Beste Heren,

Waarschijnlijk zijn jullie hier al van op de hoogte maar nog even voor de 
zekerheid, ik krijg deze melding ook nog met de 1.0 Private Beta zodra ik een 
visualisatie probeer te doen (OSX, 64bit).

Groeten,
Marijn


2010-08-16 13:23:32,253 INFO  org.bimserver.Server - Starting 
server...localhost 80822010-08-16 13:23:32,315 INFO  org.bimserver.Server - 
Starting web server...2010-08-16 13:23:32,318 INFO  org.eclipse.jetty.util.log 
- jetty-7.1.6.v20100715
2010-08-16 13:23:32,738 INFO  org.bimserver.ServerInitializer - Starting 
ServerInitializer2010-08-16 13:23:32,739 INFO  org.bimserver.ServerInitializer 
- Detected server type: STANDALONE_JAR (Mac OS X, 64bit)2010-08-16 13:23:33,020 
INFO  org.bimserver.ServerInitializer - IFC-Schema file found
2010-08-16 13:23:34,048 INFO  org.bimserver.ServerInitializer - IFC-Schema 
succesfully loaded2010-08-16 13:23:35,848 INFO  
org.bimserver.ifc.FileFieldIgnoreMap - Reading general ignore list from 
"Users/marijn/Downloads/bimserver-1.0PBeta/config/ignore.xml"
2010-08-16 13:23:35,854 INFO  org.bimserver.services.TokenManager - Cleaning up 
tokens2010-08-16 13:23:35,994 INFO  org.bimserver.ifc.FileFieldIgnoreMap - 
Reading specific non-ignore list for IfcBuildingStorey from 
"Users/marijn/Downloads/bimserver-1.0PBeta/config/ignoreexceptions/IfcBuildingSt
orey.xml"
2010-08-16 13:23:36,014 INFO  org.bimserver.TemplateEngine - Using 
"Users/marijn/Downloads/bimserver-1.0PBeta/config/templates/" as template 
dir2010-08-16 13:23:36,116 INFO  
org.bimserver.database.berkeley.BerkeleyColumnDatabase - No database directory 
found, creating "/Users/marijn/Downloads/bimserver-1.0PBeta/database"
2010-08-16 13:23:36,116 INFO  
org.bimserver.database.berkeley.BerkeleyColumnDatabase - Succesfully created 
database dir "/Users/marijn/Downloads/bimserver-1.0PBeta/database"2010-08-16 
13:23:36,378 INFO  org.bimserver.database.berkeley.BerkeleyColumnDatabase - 
Berkeley Database Init done 258 ms
2010-08-16 13:23:37,241 INFO  org.bimserver.ServerInitializer - Using 
/Users/marijn/Downloads/bimserver-1.0PBeta/config/IFC2X3_FINAL.exp as engine 
schema2010-08-16 13:23:37,377 INFO  org.eclipse.jetty.util.log - Started 
SocketConnector@localhost:8082
2010-08-16 13:23:37,377 INFO  org.bimserver.Server - Webserver succesfully 
started2010-08-16 13:23:37,377 INFO  org.bimserver.Server - Server started 
succesfully, click on the "launch webbrowser" button, or go to: 
http://localhost:8082
2010-08-16 13:25:10,124 INFO  org.bimserver.ifcengine.EngineProces - java 
-Djna.library.path=lib/64 
-Djava.io.tmpdir=/Users/marijn/Downloads/bimserver-1.0PBeta/tmp -classpath 
/Users/marijn/Downloads/bimserver-1.0PBeta/lib/slf4j-log4j12-1.6.0.jar:/Users/ma
rijn/Downloads/bimserver-1.0PBeta/lib/slf4j-api-1.6.0.jar:/Users/marijn/Download
s/bimserver-1.0PBeta/lib/log4j-1.2.16.jar:/Users/marijn/Downloads/bimserver-1.0P
Beta/lib/bimserver.jar:/Users/marijn/Downloads/bimserver-1.0PBeta/lib/jna.jar:/U
sers/marijn/Downloads/bimserver-1.0PBeta/lib/org.eclipse.emf_2.5.0.v200906151043
.jar:/Users/marijn/Downloads/bimserver-1.0PBeta/lib/org.eclipse.emf.common_2.5.0
.v200906151043.jar:/Users/marijn/Downloads/bimserver-1.0PBeta/lib/org.eclipse.em
f.ecore_2.5.0.v200906151043.jar:/Users/marijn/Downloads/bimserver-1.0PBeta/lib/o
rg.eclipse.emf.ecore.xmi_2.5.0.v200906151043.jar: -Xmx512m 
org.bimserver.ifcengine.IfcEngineServer 20001 
/Users/marijn/Downloads/bimserver-1.0PBeta/config/IFC2X3_FINAL.exp 
/Users/marijn/Downloads/bimserver-1.0PBeta/lib
2010-08-16 13:25:10,626 INFO  org.bimserver.utils.StreamReaderToLog - Exception 
in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 
'IFCEngine': dlopen(libIFCEngine.dylib, 9): image not found
2010-08-16 13:25:10,627 INFO  org.bimserver.utils.StreamReaderToLog -   at 
com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:164)2010-08-16 
13:25:10,627 INFO  org.bimserver.utils.StreamReaderToLog -  at 
com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:237)
2010-08-16 13:25:10,627 INFO  org.bimserver.utils.StreamReaderToLog -   at 
com.sun.jna.Library$Handler.<init>(Library.java:140)2010-08-16 13:25:10,627 
INFO  org.bimserver.utils.StreamReaderToLog -   at 
com.sun.jna.Native.loadLibrary(Native.java:375)
2010-08-16 13:25:10,627 INFO  org.bimserver.utils.StreamReaderToLog -   at 
com.sun.jna.Native.loadLibrary(Native.java:360)2010-08-16 13:25:10,627 INFO  
org.bimserver.utils.StreamReaderToLog -     at 
org.bimserver.ifcengine.IfcEngineInterface.<clinit>(IfcEngineInterface.java:16)
2010-08-16 13:25:10,627 INFO  org.bimserver.utils.StreamReaderToLog -   at 
org.bimserver.ifcengine.IfcEngineJNA.<init>(IfcEngineJNA.java:47)2010-08-16 
13:25:10,628 INFO  org.bimserver.utils.StreamReaderToLog -  at 
org.bimserver.ifcengine.IfcEngineServer.<init>(IfcEngineServer.java:40)
2010-08-16 13:25:10,628 INFO  org.bimserver.utils.StreamReaderToLog -   at 
org.bimserver.ifcengine.IfcEngineServer.main(IfcEngineServer.java:33)2010-08-16 
13:25:12,042 WARN  org.eclipse.jetty.util.log - 
/downloadjava.lang.NullPointerException
    at org.bimserver.ifcengine.FailSafeIfcEngine.writeCommand(FailSafeIfcEngine.java:100)   at org.bimserver.ifcengine.FailSafeIfcEngine.openModel(FailSafeIfcEngine.java:67)   at org.bimserver.o3d.O3dJsonSerializer.setGeometry(O3dJsonSerializer.java:233)
    at org.bimserver.o3d.O3dJsonSerializer.createScene(O3dJsonSerializer.java:162)  at org.bimserver.o3d.O3dJsonSerializer.write(O3dJsonSerializer.java:78) at org.bimserver.ifc.EmfSerializer.writeToOutputStream(EmfSerializer.java:123)
    at org.bimserver.servlets.DownloadServlet.service(DownloadServlet.java:138) at javax.servlet.http.HttpServlet.service(HttpServlet.java:806) at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:527)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:423)   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:493)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:930)    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:358)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:866) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:113)  at org.eclipse.jetty.server.Server.handle(Server.java:351)  at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:594)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1059) at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:764) at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:217)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:424)  at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:241) at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:436)
    at java.lang.Thread.run(Thread.java:637)java:358)   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:866

```

Original issue reported on code.google.com by `berlo...@gmail.com` on 19 Aug 2010 at 11:12

**Comment by GoogleCodeExporter** [comment]
Original comment by `berlo...@gmail.com` on 24 Aug 2010 at 2:43
- Added labels: **Priority-Medium**
- Removed labels: **Priority-Low**

**Comment by GoogleCodeExporter** [comment]
Original comment by `berlo...@gmail.com` on 13 Sep 2010 at 4:23
- Added labels: **Milestone-Release1.0**, **Priority-Low**
- Removed labels: **Milestone-Release1.1**, **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
Original comment by `berlo...@gmail.com` on 14 Sep 2010 at 12:37
- Changed state: **Fixed**
