### ISSUE TITLE
storing two files at the same time

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bmor1/bimserver#340]
```
What steps will reproduce the problem?
1. upload file in subproject A and wait till 'storing' starts
2. logout
3. login as other users and upload new file in subproject B
4. logout and login as admin
5. wait.....
wait a long time.....

the storing of the models takes very long when it is done en parallel
```

Original issue reported on code.google.com by `berlo...@gmail.com` on 16 Nov 2011 at 8:46

**Comment by GoogleCodeExporter** [comment]
```
eventualy:


2011-11-16 21:47:04,224 ERROR project.jsp - 
org.eclipse.jetty.io.RuntimeIOException: org.eclipse.jetty.io.EofException
    at org.eclipse.jetty.io.UncheckedPrintWriter.setError(UncheckedPrintWriter.java:107)
    at org.eclipse.jetty.io.UncheckedPrintWriter.write(UncheckedPrintWriter.java:234)
    at org.apache.jasper.runtime.JspWriterImpl.flushBuffer(JspWriterImpl.java:181)
    at org.apache.jasper.runtime.JspWriterImpl.write(JspWriterImpl.java:449)
    at org.apache.jasper.runtime.JspWriterImpl.write(JspWriterImpl.java:462)
    at org.apache.jsp.project_jsp._jspService(org.apache.jsp.project_jsp:1096)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:109)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:389)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:486)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:380)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:538)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:478)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:517)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:937)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:871)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
    at org.eclipse.jetty.server.Server.handle(Server.java:346)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:438)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:901)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:562)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:214)
    at org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:47)
    at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:242)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:529)
    at java.lang.Thread.run(Unknown Source)
Caused by: org.eclipse.jetty.io.EofException
    at org.eclipse.jetty.http.HttpGenerator.flushBuffer(HttpGenerator.java:916)
    at org.eclipse.jetty.http.AbstractGenerator.flush(AbstractGenerator.java:433)
    at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:89)
    at org.eclipse.jetty.server.HttpConnection$Output.flush(HttpConnection.java:992)
    at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:172)
    at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:96)
    at java.io.ByteArrayOutputStream.writeTo(Unknown Source)
    at org.eclipse.jetty.server.HttpWriter.write(HttpWriter.java:283)
    at org.eclipse.jetty.io.UncheckedPrintWriter.write(UncheckedPrintWriter.java:225)
    ... 30 more
Caused by: java.net.SocketException: Software caused connection abort: socket 
write error
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(Unknown Source)
    at java.net.SocketOutputStream.write(Unknown Source)
    at org.eclipse.jetty.io.ByteArrayBuffer.writeTo(ByteArrayBuffer.java:354)
    at org.eclipse.jetty.io.bio.StreamEndPoint.flush(StreamEndPoint.java:151)
    at org.eclipse.jetty.io.bio.StreamEndPoint.flush(StreamEndPoint.java:181)
    at org.eclipse.jetty.http.HttpGenerator.flushBuffer(HttpGenerator.java:843)
    ... 38 more

```

Original comment by `berlo...@gmail.com` on 16 Nov 2011 at 8:48

**Comment by GoogleCodeExporter** [comment]
Original comment by `ru...@logic-labs.nl` on 13 Dec 2011 at 12:21

**Comment by GoogleCodeExporter** [comment]
Original comment by `ru...@logic-labs.nl` on 13 Dec 2011 at 1:10
- Changed title: **storing two files at the same time**

**Comment by GoogleCodeExporter** [comment]
```
cannot reproduce... 
looks like a timeout
```

Original comment by `berlo...@gmail.com` on 13 Jan 2012 at 12:25
- Removed labels: **Milestone-Release1.1**

**Comment by GoogleCodeExporter** [comment]
Original comment by `berlo...@gmail.com` on 9 Apr 2012 at 9:02
- Changed state: **Fixed**
