### ISSUE TITLE
checkin as new revision doesn't work

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bmor1/bimserver#342]
```
What steps will reproduce the problem?
1. use 'checkin as new revision'
2.
3.

getting error:


2011-11-16 21:51:49,249 ERROR org.bimserver.longaction.LongCheckinAction - 
java.lang.NullPointerException
    at org.bimserver.database.actions.CheckinPart2DatabaseAction.execute(CheckinPart2DatabaseAction.java:122)
    at org.bimserver.database.actions.CheckinPart2DatabaseAction.execute(CheckinPart2DatabaseAction.java:42)
    at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:496)
    at org.bimserver.longaction.LongCheckinAction.execute(LongCheckinAction.java:62)
    at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:46)
    at java.lang.Thread.run(Unknown Source)


```

Original issue reported on code.google.com by `berlo...@gmail.com` on 16 Nov 2011 at 8:54

**Comment by GoogleCodeExporter** [comment]
Original comment by `berlo...@gmail.com` on 16 Nov 2011 at 8:58
- Changed state: **Invalid**
