### ISSUE TITLE
branching to new project doesn't work

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bmor1/bimserver#343]
```
What steps will reproduce the problem?
1. select revision
2. fill out name and comment
3. click 'branche'

What is the expected output? What do you see instead?
expect: new project
getting: 'null' 

error in console:
2011-11-16 21:58:24,488 ERROR org.bimserver.longaction.LongCheckinAction - 
java.lang.NullPointerException
    at org.bimserver.database.actions.CheckinPart2DatabaseAction.execute(CheckinPart2DatabaseAction.java:122)
    at org.bimserver.database.actions.CheckinPart2DatabaseAction.execute(CheckinPart2DatabaseAction.java:42)
    at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:496)
    at org.bimserver.longaction.LongCheckinAction.execute(LongCheckinAction.java:62)
    at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:46)
    at java.lang.Thread.run(Unknown Source)

```

Original issue reported on code.google.com by `berlo...@gmail.com` on 16 Nov 2011 at 8:59

**Comment by GoogleCodeExporter** [comment]
```
PS: project ís created but no revision
```

Original comment by `berlo...@gmail.com` on 16 Nov 2011 at 9:03

**Comment by GoogleCodeExporter** [comment]
Original comment by `ru...@logic-labs.nl` on 7 Dec 2011 at 2:47
- Changed state: **Fixed**
