### ISSUE TITLE
BufferUnderflowException on database migration

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bmor1/bimserver#367]
```
What steps will reproduce the problem?
1. start bimserver (localdev)
2. open webbrowser and see 'migration screen'
3. click migrate.

error:


HTTP ERROR 500

Problem accessing /migrations.jsp;jsessionid=h76yln8ucl6016fvoemi2wya5. Reason:

    Server Error
Caused by:

java.nio.BufferUnderflowException
    at java.nio.Buffer.nextGetIndex(Unknown Source)
    at java.nio.HeapByteBuffer.getShort(Unknown Source)
    at org.bimserver.database.DatabaseSession.convertByteArrayToObject(DatabaseSession.java:332)
    at org.bimserver.database.DatabaseSession.lazyLoad(DatabaseSession.java:1011)
    at org.bimserver.database.DatabaseSession.lazyLoad(DatabaseSession.java:1000)
    at org.bimserver.database.DatabaseSession.load(DatabaseSession.java:1020)
    at org.bimserver.emf.IdEObjectImpl.load(IdEObjectImpl.java:118)
    at org.bimserver.emf.IdEObjectImpl.eGet(IdEObjectImpl.java:81)
    at org.eclipse.emf.ecore.util.EcoreEList.contains(EcoreEList.java:376)
    at org.eclipse.emf.common.util.AbstractEList.add(AbstractEList.java:301)
    at org.bimserver.database.DatabaseSession.convertByteArrayToObject(DatabaseSession.java:301)
    at org.bimserver.database.DatabaseSession.convertByteArrayToObject(DatabaseSession.java:245)
    at org.bimserver.database.DatabaseSession.getMap(DatabaseSession.java:812)
    at org.bimserver.database.DatabaseSession.getMap(DatabaseSession.java:840)
    at org.bimserver.database.DatabaseSession.query(DatabaseSession.java:1060)
    at org.bimserver.database.DatabaseSession.querySingle(DatabaseSession.java:1078)
    at org.bimserver.database.DatabaseSession.querySingle(DatabaseSession.java:1074)
    at org.bimserver.BimServer.createDatabaseObjects(BimServer.java:360)
    at org.bimserver.BimServer.initDatabaseDependantItems(BimServer.java:445)
    at org.bimserver.BimServer.access$3(BimServer.java:441)
    at org.bimserver.BimServer$3.stateChanged(BimServer.java:284)
    at org.bimserver.ServerInfoManager.notifyStateChangeListeners(ServerInfoManager.java:50)
    at org.bimserver.ServerInfoManager.setServerState(ServerInfoManager.java:101)
    at org.bimserver.ServerInfoManager.update(ServerInfoManager.java:84)
    at org.bimserver.webservices.Service.migrateDatabase(Service.java:1812)
    at org.apache.jsp.migrations_jsp._jspService(org.apache.jsp.migrations_jsp:72)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:109)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:389)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:486)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:380)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:538)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:478)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:517)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:937)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:871)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
    at org.eclipse.jetty.server.Server.handle(Server.java:346)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:438)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:921)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:780)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:220)
    at org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:55)
    at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:242)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:529)
    at java.lang.Thread.run(Unknown Source)
Powered by Jetty://


















```

Original issue reported on code.google.com by `berlo...@gmail.com` on 25 Jan 2012 at 12:04

**Comment by GoogleCodeExporter** [comment]
```
That's because I'm editing older migrations all the time, we haven't released 
yet.
```

Original comment by `ru...@logic-labs.nl` on 26 Jan 2012 at 1:41
- Changed state: **Close**
