### ISSUE TITLE
Unable to load IFCEngine on 64-bit Linux (java.lang.UnsatisfiedLinkError)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bmor1/bimserver#385]
```
What steps will reproduce the problem?
1. Try to use the IfcEngine plug-in on 64-bit Linux.

What is the expected output? What do you see instead?

The following exception (full stack below):

11:12:38 ERROR java.lang.UnsatisfiedLinkError: Unable to load library 
'IFCEngine': 
/home/kvholm/workspace/BimCombined/home/tmp/IfcEngineBonsma/libIFCEngine.so: 
undefined symbol: __gxx_personality_v0 
(org.bimserver.ifcengine.FailSafeIfcEngine.java:165) 

What version of the product are you using? On what operating system?

trunk, r1741. Ubuntu 10.04 64-bit

Please provide any additional information below.

Call stack:

11:12:38 ERROR java.lang.UnsatisfiedLinkError: Unable to load library 
'IFCEngine': 
/home/kvholm/workspace/BimCombined/home/tmp/IfcEngineBonsma/libIFCEngine.so: 
undefined symbol: __gxx_personality_v0 
(org.bimserver.ifcengine.FailSafeIfcEngine.java:165) 
11:12:38 ERROR 
                                                                                (org.bimserver.ifcengine.FailSafeIfcEngine.java:165) 
11:12:38 ERROR  at 
com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:164)                
(org.bimserver.ifcengine.FailSafeIfcEngine.java:165) 
11:12:38 ERROR 
                                                                                (org.bimserver.ifcengine.FailSafeIfcEngine.java:165) 
11:12:38 ERROR  at 
com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:237)                
(org.bimserver.ifcengine.FailSafeIfcEngine.java:165) 
11:12:38 ERROR 
                                                                                (org.bimserver.ifcengine.FailSafeIfcEngine.java:165) 
11:12:38 ERROR  at com.sun.jna.Library$Handler.<init>(Library.java:140)         
                (org.bimserver.ifcengine.FailSafeIfcEngine.java:165) 
11:12:38 ERROR 
                                                                                (org.bimserver.ifcengine.FailSafeIfcEngine.java:165) 
11:12:38 ERROR  at com.sun.jna.Native.loadLibrary(Native.java:375)              
                (org.bimserver.ifcengine.FailSafeIfcEngine.java:165) 
11:12:38 ERROR 
                                                                                (org.bimserver.ifcengine.FailSafeIfcEngine.java:165) 
11:12:38 ERROR  at com.sun.jna.Native.loadLibrary(Native.java:360)              
                (org.bimserver.ifcengine.FailSafeIfcEngine.java:165) 
11:12:38 ERROR 
                                                                                (org.bimserver.ifcengine.FailSafeIfcEngine.java:165) 
11:12:38 ERROR  at 
org.bimserver.ifcengine.IfcEngineInterface.<clinit>(IfcEngineInterface.java:39) 
(org.bimserver.ifcengine.FailSafeIfcEngine.java:165) 
11:12:38 ERROR 
                                                                                (org.bimserver.ifcengine.FailSafeIfcEngine.java:165) 
11:12:38 ERROR  at 
org.bimserver.ifcengine.jvm.IfcEngine.<init>(IfcEngine.java:66)              
(org.bimserver.ifcengine.FailSafeIfcEngine.java:165) 
11:12:38 ERROR 
                                                                                (org.bimserver.ifcengine.FailSafeIfcEngine.java:165) 
11:12:38 ERROR  at 
org.bimserver.ifcengine.jvm.IfcEngineServer.<init>(IfcEngineServer.java:71)  
(org.bimserver.ifcengine.FailSafeIfcEngine.java:165) 
11:12:38 ERROR 
                                                                                (org.bimserver.ifcengine.FailSafeIfcEngine.java:165) 
11:12:38 ERROR  at 
org.bimserver.ifcengine.jvm.IfcEngineServer.main(IfcEngineServer.java:59)    
(org.bimserver.ifcengine.FailSafeIfcEngine.java:165) 
11:12:38 ERROR 
```

Original issue reported on code.google.com by `kristian...@catenda.no` on 16 Mar 2012 at 10:23

**Comment by GoogleCodeExporter** [comment]
```
is this still an issue in the RC2?
```

Original comment by `berlo...@gmail.com` on 9 Apr 2012 at 9:04
- Added labels: **Milestone-Release1.1**

**Comment by GoogleCodeExporter** [comment]
```
This does work in RC2
```

Original comment by `ru...@logic-labs.nl` on 10 Apr 2012 at 7:44
- Changed state: **Fixed**
