### ISSUE TITLE
Investige which file is causing this error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bmor1/bimserver#394]
```
org.bimserver.database.BimserverDatabaseException: Cannot store reference to 
object IfcBuildingElementProxy with oid=-1, pid=0, rid=0 referenced from 
IfcRelContainedInSpatialStructure with oid=35331364, feature RelatedElements
    at org.bimserver.database.DatabaseSession.writeReference(DatabaseSession.java:1366)
    at org.bimserver.database.DatabaseSession.convertObjectToByteArray(DatabaseSession.java:430)
    at org.bimserver.database.DatabaseSession.commit(DatabaseSession.java:192)
    at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:549)
    at org.bimserver.longaction.LongCheckinAction.execute(LongCheckinAction.java:48)
    at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:53)
    at java.lang.Thread.run(Thread.java:722)

```

Original issue reported on code.google.com by `ru...@logic-labs.nl` on 20 Apr 2012 at 10:17

**Comment by GoogleCodeExporter** [comment]
```
Had a similar issue in a model. I think I tracked it down to a bug in 
IfcStepDeserializer. If a list contains unset attribute values ($) the value is 
not added to a list, but the list index is still incremented. If the list 
contains referenced objects (#) after the $ value, its WaitingObject index will 
not match its place in the list, and resolving the reference will break. See 
attached patch. 
```

Original comment by `kristian...@catenda.no` on 11 May 2012 at 8:29

Attachments:
- [IfcStepDeserializer.patch](https://storage.googleapis.com/google-code-attachments/bimserver/issue-394/comment-1/IfcStepDeserializer.patch)

**Comment by GoogleCodeExporter** [comment]
```
Are there any plans to include this patch soon? There seems to be quite a lot 
of Ifc files that suffers from this problem.
```

Original comment by `lars.bjo...@catenda.no` on 12 Sep 2012 at 9:36

**Comment by GoogleCodeExporter** [comment]
```
The supplied patch did not resolve the error for the file Catenda gave me in my 
current version of BIMserver, I have fixed this bug with a different patch in 
trunk now.
```

Original comment by `ru...@logic-labs.nl` on 27 Sep 2012 at 8:19
- Changed state: **Fixed**
