### ISSUE TITLE
Problem calling ServiceInterface.downloadRevisions using Protocol Buffers

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bmor1/bimserver#398]
```
What steps will reproduce the problem?
1. Call ServiceInterface.downloadRevisions using the Protocol Buffers interface.

What is the expected output? What do you see instead?

Expected the method to return an action ID, instead the following exception is 
thrown:

java.lang.IllegalArgumentException: Wrong object type used with protocol 
message reflection.
    at com.google.protobuf.FieldSet.setField(FieldSet.java:199)
    at com.google.protobuf.DynamicMessage$Builder.setField(DynamicMessage.java:380)
    at org.bimserver.shared.pb.Reflector.callMethod(Reflector.java:90)
    at org.bimserver.pb.ServiceInterfaceReflectorImpl.downloadRevisions(ServiceInterfaceReflectorImpl.java:67)


What version of the product are you using? On what operating system?

trunk, r1844
```

Original issue reported on code.google.com by `kristian...@catenda.no` on 23 Apr 2012 at 12:06

**Comment by GoogleCodeExporter** [comment]
Original comment by `berlo...@gmail.com` on 23 Apr 2012 at 12:07
- Added labels: **Milestone-Release1.1**

**Comment by GoogleCodeExporter** [comment]
Original comment by `berlo...@gmail.com` on 23 Apr 2012 at 1:13
- Changed state: **Fixed**
