### ISSUE TITLE
Client Creation Error BimServerClientFactory

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bmor1/bimserver#445]
```
This simple code on trunk 2428:

BimServerClientFactory client =  new 
JsonBimServerClientFactory("http://localhost:8080");        

BimServerClient bimServerClient = client.create(new 
UsernamePasswordAuthenticationInfo("admin@bimserver.org", "admin"));

Gives this error:
java.lang.NullPointerException
    at org.bimserver.generated.AuthInterfaceImpl1.login(AuthInterfaceImpl1.java)
    at org.bimserver.client.BimServerClient.authenticate(BimServerClient.java:97)
    at org.bimserver.client.BimServerClient.connect(BimServerClient.java:90)
    at org.bimserver.client.BimServerClient.setAuthentication(BimServerClient.java:83)
    at org.bimserver.client.JsonBimServerClientFactory.create(JsonBimServerClientFactory.java:52)
    at org.bimserver.tests.loader.main(loader.java:21)


```

Original issue reported on code.google.com by `paologal...@gmail.com` on 21 Mar 2013 at 10:16

**Comment by GoogleCodeExporter** [comment]
Original comment by `berlo...@gmail.com` on 21 Mar 2013 at 8:14
- Added labels: **Milestone-Release1.2**

**Comment by GoogleCodeExporter** [comment]
Original comment by `ru...@logic-labs.nl` on 26 Mar 2013 at 7:52
- Changed state: **Fixed**
