### ISSUE TITLE
Error in IFC checkin 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bmor1/bimserver#451]
```
Hi all, 

I got source 2473, Ubuntu linux with jdk 1.7, build via Ant a War file and then 
deployed on 7.0.39 tomcat.
Tried to upload an IFC file from test data, bimserver creates project but here 
is the error in bimserver.log:

15:58:19 ERROR                                                                  
                (org.bimserver.database.actions.CheckinDatabaseAction.java:163)
java.lang.NoSuchMethodError: 
org.apache.tomcat.util.http.fileupload.ByteArrayOutputStream.size()I
        at org.bimserver.GeometryGenerator.generateGeometry(GeometryGenerator.java:126)
        at org.bimserver.database.actions.CheckinDatabaseAction.execute(CheckinDatabaseAction.java:134)
        at org.bimserver.database.actions.CheckinDatabaseAction.execute(CheckinDatabaseAction.java:56)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:508)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:496)
        at org.bimserver.longaction.LongCheckinAction.execute(LongCheckinAction.java:49)
        at org.bimserver.longaction.LongActionManager$1.run(LongActionManager.java:43)
        at java.lang.Thread.run(Thread.java:722)

Unchecking "creating geometry at checkin" fixes the problem (now the file is 
listed in bimsurfer client) but not visible in client due to error (from 
firebug):

TypeError: data.data is undefined

data.data.ifcTypes.sort();   (app.js row 1809)


```

Original issue reported on code.google.com by `paologal...@gmail.com` on 12 Apr 2013 at 2:31

**Comment by GoogleCodeExporter** [comment]
```
All worked fine on eclipse IDE in windows 7...  
```

Original comment by `paologal...@gmail.com` on 12 Apr 2013 at 3:59

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting! Somehow 
org.apache.tomcat.util.http.fileupload.ByteArrayOutputStream was being used, 
which makes no sense, java.io.ByteArrayOutputStream is fine, so I changed it to 
that. So no conflict between Tomcat versions anymore.
```

Original comment by `ru...@logic-labs.nl` on 15 Apr 2013 at 8:13
- Changed state: **Fixed**
