### ISSUE TITLE
query objecttype doesn't work

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bmor1/bimserver#60]
```
gives error:


HTTP ERROR 500

Problem accessing /download. Reason:

    Transaction 1053 has been closed and is no longer usable.
Caused by:

java.lang.IllegalArgumentException: Transaction 1053 has been closed and is no 
longer usable.
    at com.sleepycat.je.Transaction.getLocker(Transaction.java:728)
    at com.sleepycat.je.DbInternal.getLocker(DbInternal.java:281)
    at com.sleepycat.je.txn.LockerFactory.getReadableLocker(LockerFactory.java:156)
    at com.sleepycat.je.Database.get(Database.java:898)
    at org.bimserver.database.berkeley.BerkeleyColumnDatabase.get(BerkeleyColumnDatabase.java:172)
    at org.bimserver.database.DatabaseSession.get(DatabaseSession.java:311)
    at org.bimserver.database.DatabaseSession.get(DatabaseSession.java:1083)
    at org.bimserver.database.DatabaseSession.getRevisionByRoid(DatabaseSession.java:1072)
    at org.bimserver.Service.downloadOfType(Service.java:733)
    at org.bimserver.shared.AuthenticatedServiceWrapper.downloadOfType(AuthenticatedServiceWrapper.java:105)
    at org.bimserver.servlets.DownloadServlet.service(DownloadServlet.java:104)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:527)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:423)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:493)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:930)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:358)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:866)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:113)
    at org.eclipse.jetty.server.Server.handle(Server.java:351)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:594)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1059)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:764)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:217)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:424)
    at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:241)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:436)
    at java.lang.Thread.run(Unknown Source)
Powered by Jetty://


















```

Original issue reported on code.google.com by `berlo...@gmail.com` on 27 Aug 2010 at 9:04

**Comment by GoogleCodeExporter** [comment]
Original comment by `rdlsoftware@gmail.com` on 30 Aug 2010 at 3:47
- Changed state: **Fixed**
